"use client";

import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { AdminGradeError, adminGradeService } from "../../services/admin-grade-service";
import type { AdminGrade, CreateGradeInput } from "../../types/grade";
import { GradeFormModal } from "./grade-form-modal";

const Badge = ({ active }: { active: boolean }) => <span className={`inline-flex min-h-7 shrink-0 self-start items-center justify-center whitespace-nowrap rounded-full px-3 py-1 text-xs font-extrabold leading-none ${active ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-700"}`}>{active ? "نشط" : "غير نشط"}</span>;
export function AdminGradesPage() {
  const router = useRouter(); const [grades, setGrades] = useState<AdminGrade[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<AdminGrade | null>(null); const [formOpen, setFormOpen] = useState(false); const [busyId, setBusyId] = useState<number | null>(null); const [reordering, setReordering] = useState(false);
  const unauthorized = useCallback((requestError: unknown) => { if (requestError instanceof AdminGradeError && requestError.kind === "unauthorized") { router.replace("/admin/login"); return true; } return false; }, [router]);
  const refresh = useCallback(async () => { const items = await adminGradeService.getGrades("all"); setGrades(items); setError(null); }, []);
  useEffect(() => { let active = true; adminGradeService.getGrades("all").then((items) => { if (active) { setGrades(items); setLoading(false); } }).catch((requestError: unknown) => { if (active && !unauthorized(requestError)) { setError("تعذر تحميل الصفوف. حاول مجددًا."); setLoading(false); } }); return () => { active = false; }; }, [unauthorized]);
  async function save(input: CreateGradeInput) { if (editing) await adminGradeService.updateGrade(editing.id, { ...input, sortOrder: input.sortOrder ?? editing.sortOrder }); else await adminGradeService.createGrade(input); await refresh(); setFormOpen(false); setEditing(null); }
  async function toggle(grade: AdminGrade) { if (grade.isActive && !window.confirm("تعطيل الصف؟\n\nتعطيل الصف سيمنع ظهوره ومواده للطلاب، لكنه لن يحذف البيانات.")) return; setBusyId(grade.id); try { await adminGradeService.updateGradeStatus(grade.id, !grade.isActive); await refresh(); } catch (requestError) { if (!unauthorized(requestError)) setError("تعذر تحديث حالة الصف."); } finally { setBusyId(null); } }
  async function move(index: number, offset: -1 | 1) { const next = [...grades]; const target = index + offset; [next[index], next[target]] = [next[target]!, next[index]!]; const ordered = next.map((grade, itemIndex) => ({ ...grade, sortOrder: itemIndex + 1 })); setGrades(ordered); setReordering(true); try { await adminGradeService.reorderGrades({ items: ordered.map(({ id, sortOrder }) => ({ id, sortOrder })) }); await refresh(); } catch (requestError) { if (!unauthorized(requestError)) { setError("تعذر حفظ الترتيب، تمت استعادة ترتيب الخادم."); await refresh().catch(() => undefined); } } finally { setReordering(false); } }
  const actions = (grade: AdminGrade, index: number) => <div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setEditing(grade); setFormOpen(true); }} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold">تعديل</button><button type="button" onClick={() => void toggle(grade)} disabled={busyId === grade.id} className="rounded-lg border border-amber-300 px-3 py-2 text-sm font-bold">{grade.isActive ? "تعطيل" : "تفعيل"}</button><button type="button" onClick={() => router.push(`/admin/dashboard/subjects?gradeId=${String(grade.id)}`)} className="rounded-lg border border-[var(--sanabil-gold)] px-3 py-2 text-sm font-bold">عرض المواد</button><button type="button" aria-label="تحريك لأعلى" onClick={() => void move(index, -1)} disabled={index === 0 || reordering}>↑</button><button type="button" aria-label="تحريك لأسفل" onClick={() => void move(index, 1)} disabled={index === grades.length - 1 || reordering}>↓</button></div>;
  return <div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-bold text-[var(--sanabil-gold-dark)]">إدارة المحتوى</p><h1 className="mt-1 text-3xl font-black">الصفوف الدراسية</h1><p className="mt-2 text-sm leading-7 text-slate-600">أضف الصفوف وعدّل ترتيب ظهورها وحالتها للطلاب.</p></div><button type="button" onClick={() => { setEditing(null); setFormOpen(true); }} className="min-h-11 rounded-xl bg-[var(--sanabil-navy)] px-5 font-extrabold text-white">إضافة صف</button></div>{error ? <p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 font-semibold text-red-800">{error}</p> : null}<section aria-busy={loading} className="mt-7">{loading ? <p className="rounded-2xl bg-white p-8 text-center font-bold">جارٍ تحميل الصفوف...</p> : grades.length === 0 ? <p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center font-bold">لا توجد صفوف حاليًا.</p> : <><div className="hidden overflow-hidden rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full text-right"><thead className="bg-slate-100"><tr><th className="p-4">اسم الصف</th><th className="p-4">slug</th><th className="p-4">الترتيب</th><th className="p-4">الحالة</th><th className="p-4">عدد المواد</th><th className="p-4">الإجراءات</th></tr></thead><tbody className="divide-y divide-slate-200">{grades.map((grade, index) => <tr key={grade.id}><td className="p-4 font-extrabold">{grade.name}</td><td className="p-4"><code dir="ltr">{grade.slug}</code></td><td className="p-4">{grade.sortOrder}</td><td className="p-4"><Badge active={grade.isActive} /></td><td className="p-4">{grade.subjectCount}</td><td className="p-4">{actions(grade, index)}</td></tr>)}</tbody></table></div><div className="grid gap-4 md:hidden">{grades.map((grade, index) => <article key={grade.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><div><h2 className="font-extrabold">{grade.name}</h2><code dir="ltr" className="text-xs text-slate-600">{grade.slug}</code></div><Badge active={grade.isActive} /></div><p className="mt-3 text-sm">الترتيب: {grade.sortOrder} · عدد المواد: {grade.subjectCount}</p><div className="mt-4">{actions(grade, index)}</div></article>)}</div></>}</section>{formOpen ? <GradeFormModal key={editing?.id ?? "new"} grade={editing} onClose={() => { setFormOpen(false); setEditing(null); }} onSave={save} onUnauthorized={() => router.replace("/admin/login")} /> : null}</div>;
}
