// @vitest-environment jsdom
import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ list: vi.fn(), create: vi.fn(), update: vi.fn(), status: vi.fn(), reorder: vi.fn(), replace: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ replace: mocks.replace }) }));
vi.mock("../../services/admin-announcement-service", () => ({ AdminAnnouncementError: class AdminAnnouncementError extends Error { constructor(public kind: string, public fields = {}) { super(kind); } }, adminAnnouncementService: { getAnnouncements: mocks.list, createAnnouncement: mocks.create, updateAnnouncement: mocks.update, updateStatus: mocks.status, reorder: mocks.reorder } }));
import { AdminAnnouncementsPage } from "./admin-announcements-page";
const item = { id: 1, title: "إعلان أول", content: "محتوى", badge: "مهم", imageUrl: null, ctaLabel: null, ctaUrl: null, sortOrder: 1, isActive: true, startsAt: null, endsAt: null, createdAt: "2026", updatedAt: "2026" };
beforeEach(() => { vi.clearAllMocks(); mocks.list.mockResolvedValue([item, { ...item, id: 2, title: "إعلان ثان", sortOrder: 2, isActive: false }]); mocks.create.mockResolvedValue(item); mocks.update.mockResolvedValue(item); mocks.status.mockResolvedValue(item); mocks.reorder.mockResolvedValue(null); }); afterEach(cleanup);
describe("AdminAnnouncementsPage", () => {
  it("lists, filters, changes status, and reorders", async () => { const user = userEvent.setup(); render(<AdminAnnouncementsPage />); await screen.findByText("إعلان أول"); await user.selectOptions(screen.getByLabelText("الحالة"), "active"); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ status: "active", visibility: "all" })); await user.click(screen.getByRole("button", { name: "تعطيل" })); await waitFor(() => expect(mocks.status).toHaveBeenCalledWith(1, false)); await user.click(screen.getByRole("button", { name: /تحريك إعلان أول لأسفل/ })); await waitFor(() => expect(mocks.reorder).toHaveBeenCalled()); });
  it("creates and opens editing", async () => { const user = userEvent.setup(); render(<AdminAnnouncementsPage />); await screen.findByText("إعلان أول"); await user.click(screen.getByRole("button", { name: "إضافة إعلان" })); const dialog = screen.getByRole("dialog"); await user.type(within(dialog).getByLabelText("العنوان"), "خبر جديد"); await user.type(within(dialog).getByLabelText("المحتوى"), "تفاصيل الخبر"); await user.click(within(dialog).getByRole("button", { name: "حفظ" })); await waitFor(() => expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ title: "خبر جديد", content: "تفاصيل الخبر", isActive: true }))); await user.click(screen.getAllByRole("button", { name: "تعديل" })[0]!); expect(within(screen.getByRole("dialog")).getByDisplayValue("إعلان أول")).toBeTruthy(); });
  it("keeps the CTA text when an optional image is selected", async () => { Object.defineProperty(URL, "createObjectURL", { configurable: true, value: vi.fn(() => "blob:preview") }); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: vi.fn() }); const user = userEvent.setup(); render(<AdminAnnouncementsPage />); await screen.findByText("إعلان أول"); await user.click(screen.getByRole("button", { name: "إضافة إعلان" })); const dialog = screen.getByRole("dialog"); await user.type(within(dialog).getByLabelText("العنوان"), "خبر بصورة"); await user.type(within(dialog).getByLabelText("المحتوى"), "تفاصيل"); await user.type(within(dialog).getByLabelText("نص الزر"), "اضغط للتفاصيل"); await user.type(within(dialog).getByLabelText("رابط الزر"), "https://example.com"); const image = new File([new Uint8Array([1, 2, 3])], "photo.png", { type: "image/png" }); await user.upload(within(dialog).getByLabelText(/صورة الإعلان/), image); expect((within(dialog).getByLabelText("نص الزر") as HTMLInputElement).value).toBe("اضغط للتفاصيل"); expect(within(dialog).getByRole("img", { name: "معاينة صورة الإعلان" })).toBeTruthy(); await user.click(within(dialog).getByRole("button", { name: "حفظ" })); await waitFor(() => expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ ctaLabel: "اضغط للتفاصيل", ctaUrl: "https://example.com", image, removeImage: false }))); });
});
